home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

project3/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import home
from home import views
from order import views as orderviews

urlpatterns = [
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('home/', include('home.urls')),
    path('content/', include('content.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('category/<int:id>/<slug:slug>/', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('content/<int:id>/<slug:slug>/', views.content_detail, name='content_detail'),
    path('menu/<int:id>', views.menu, name="menu"),

    path('search/', views.product_search, name='product_search'),
    path('search_auto/', views.product_search_auto, name='product_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('join/', views.join_view, name='join_view'),
    path('order/shopcart/', orderviews.shopcart, name='shopcart'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm, TextInput, Textarea, forms
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır')
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True,
                               max_length=150)
    phone = models.CharField(blank=True,
                             max_length=15)
    fax = models.CharField(blank=True,
                           max_length=15)
    email = models.CharField(blank=True,
                             max_length=50)
    smtpserver = models.CharField(blank=True,
                                  max_length=20)
    smtpemail = models.CharField(blank=True,
                                 max_length=20)
    smtppassword = models.CharField(blank=True,
                                    max_length=10)
    smtpport = models.CharField(blank=True,
                                max_length=5)
    icon = models.ImageField(blank=True,
                             upload_to='images/')
    facebook = models.CharField(blank=True,
                                max_length=50)
    instagram = models.CharField(blank=True,
                                 max_length=50)
    twitter = models.CharField(blank=True,
                               max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10,
                              choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('Read', 'Okundu'),
        ('Closed', 'Kapandı')
    )
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ContactForm(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Name'}),
            'subject': TextInput(attrs={'class': 'form-control', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'message': Textarea(attrs={'class': 'form-control', 'placeholder': 'Your Message Here', 'rows': '5'}),
        }


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=250)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + ' ' + self.user.last_name + ' (' + self.user.username + ')'

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"'.format(self.image.url))


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country', 'image']


class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır')
    )
    orderno = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10,
                              choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label='Ara', max_length=60)


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='User Name :')
    email = forms.EmailField(max_length=200, label='E-mail :')
    first_name = forms.CharField(max_length=100, help_text='First Name', label='First Name :')
    last_name = forms.CharField(max_length=100, help_text='Last Name', label='Last Name :')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

home/views.py
import json

from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from content.models import Menu, Content, CImages
from home.forms import SearchForm, SignUpForm
from home.models import Setting, ContactForm, ContactFormMessage, UserProfile
from order.models import ShopCart
from product.models import Product, Category, Images, Comment


def index(request):
    setting = Setting.objects.get(pk=1)
    sliderdata = Product.objects.all()[:4]
    category = Category.objects.all()
    menu = Menu.objects.all()
    dayproducts = Product.objects.all().order_by('?')[:6]
    lastproducts_active = Product.objects.all().order_by('-id')[:3]
    lastproducts_passive = Product.objects.all().order_by('-id')[:7]
    randomproducts = Product.objects.all().order_by('?')[:3]
    request.session['cart_items'] = ShopCart.objects.filter(user_id=request.user.id).count()
    news = Content.objects.filter(type='haber').order_by('-id')[:4]
    announcements = Content.objects.filter(type='haber').order_by('-id')[:4]

    context = {'setting': setting,
               'category': category,
               'page': 'home',
               'sliderdata': sliderdata,
               'dayproducts': dayproducts,
               'lastproducts_active': lastproducts_active,
               'lastproducts_passive': lastproducts_passive,
               'randomproducts': randomproducts,
               'menu': menu,
               'news': news,
               'announcements': announcements,
               }
    return render(request, 'index.html', context)


def hakkimizda(request):
    setting = Setting.objects.get(pk=1)
    context = {'setting': setting, 'page': 'hakkimizda'}
    return render(request, 'hakkimizda.html', context)


def referanslar(request):
    setting = Setting.objects.get(pk=1)
    context = {'setting': setting, 'page': 'referanslar'}
    return render(request, 'referanslar.html', context)


def iletisim(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            data = ContactFormMessage()
            data.name = form.cleaned_data['name']
            data.email = form.cleaned_data['email']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request, "Mesajınız başarıyla kaydedilmiştir. Teşekkür ederiz.")
            return HttpResponseRedirect('/iletisim')

    setting = Setting.objects.get(pk=1)
    form = ContactForm()
    context = {'setting': setting, 'form': form, 'page': 'iletisim'}
    return render(request, 'iletisim.html', context)


def category_products(request, id, slug):
    category = Category.objects.all()
    categorydata = Category.objects.get(pk=id)
    sliderdata = Product.objects.all().order_by('?')[:4]
    products = Product.objects.filter(category_id=id)
    context = {'products': products,
               'category': category,
               'categorydata': categorydata,
               'sliderdata': sliderdata
               }
    return render(request, 'products.html', context)


def product_detail(request, id, slug):
    category = Category.objects.all()
    product = Product.objects.get(pk=id)
    images = Images.objects.filter(product_id=id)
    comments = Comment.objects.filter(product_id=id, status='True')

    context = {'product': product,
               'category': category,
               'images': images,
               'comments': comments,
               }
    return render(request, 'product_detail.html', context)


def product_search(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            category = Category.objects.all()
            query = form.cleaned_data['query']
            products = Product.objects.filter(title__icontains=query)
            context = {'products': products,
                       'category': category,
                       }
            return render(request, 'product_search.html', context)

    return HttpResponseRedirect('/')


def product_search_auto(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        product = Product.objects.filter(title__icontains=q)
        results = []
        for rs in product:
            product_json = {}
            product_json = rs.title
            results.append(product_json)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'

    return HttpResponse(data, mimetype)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            userprofile = UserProfile.objects.get(user_id=request.user.id)
            request.session['userimage'] = userprofile.image.url
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, "Giriş Hatası! Kullanıcı adı ya da parolası yanlış.")
            return HttpResponseRedirect('/login')
    return render(request, 'login.html')


def join_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(request, username=username, password=password)
            login(request, user)
            current_user = request.user
            data = UserProfile()
            data.user_id = current_user.id
            data.image = 'images/users/user.png'
            data.save()
            return HttpResponseRedirect('/')

    form = SignUpForm()
    context = {
        'form': form,
    }
    return render(request, 'signup.html', context)

def menu(request, id):
    content = Content.objects.get(menu_id=id)

    if content:
        link = '/content/' + str(content.id) + '/menu'
        return HttpResponseRedirect(link)
    else:
        messages.warning(request, "Hata! İlgili içerik Bulunamadı")
        link = '/'
        return HttpResponseRedirect(link)

def content_detail(request, id, slug):
    menu = Menu.objects.all()
    content = Content.objects.get(pk=id)
    images = CImages.objects.filter(content_id=id)
    category = Category.objects.all()
    context = {
        'content': content,
        'menu': menu,
        'images': images,
        'category': category,
    }
    return render(request, 'content_detail.html', context)


home/templates/content_detail.html
{% extends "homebase.html" %}

{% block title %} {{ setting.title }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block head %} <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/> {% endblock %}

{% block content %}
    {% load static %}
    <section>
        <div class="container">
            <div class="row">

                    {%  include "sidebar.html" %}

                <div class="col-sm-9 padding-right">
                    <div class="features_items"><!--features_items-->
                        <h2 class="title text-center">İÇERİK AYRINTISI</h2>
                        <img src = "{{ content.image.url }}" height="300"><br>
                        <h3 class="title text-center">{{ content.title}}</h3>
                        {{ content.detail|safe }}
                        <hr>
                        {% for rs in images %}
                            <img src="{{ rs.image.url }}" height="200" alt="">
                        {% endfor %}
                    </div><!--features_items-->
                </div>
            </div>
        </div>
    </section>

{% endblock %}

home/templates/faq.html
{% extends "homebase.html" %}

{% block title %} SSS {% endblock %}
{% block head %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ categorydata.icon.url }}'/>
    <script>
            $( function() {
            $( "#accordion" ).accordion();
        } );
    </script>

{% endblock %}

{% block content %}
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Ana Sayfa</a></li>
                <li class="active">Sıkça Sorulan Sorular</li>
            </ul>
        </div>
    </div>
    <section>
        <div class="container">
            <div class="row">
                <div id="accordion">
                    {% for rs in faq %}
                        <h3>{{ rs.question }}</h3>
                        <div>
                            <p>{{ rs.answer }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

home/templates/footer.html
	<footer id="footer"><!--Footer-->
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2><span>e</span>-shopper</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Online Help</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Order Status</a></li>
								<li><a href="#">Change Location</a></li>
								<li><a href="#">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
								<li><a href="#">Womens</a></li>
								<li><a href="#">Gift Cards</a></li>
								<li><a href="#">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
								<li><a href="#">Refund Policy</a></li>
								<li><a href="#">Billing System</a></li>
								<li><a href="#">Ticket System</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">Store Location</a></li>
								<li><a href="#">Affillate Program</a></li>
								<li><a href="#">Copyright</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
					<p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
				</div>
			</div>
		</div>

	</footer><!--/Footer-->

    {% load static %}

	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'js/price-range.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

home/templates/homebase.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %} Django E-Ticaret Kitap Sitesi {% endblock %}</title>
    <meta name="keywords" content="{% block keywords %} Anasayfa anahtar kelimeler {% endblock %}">
    <meta name="description" content="{% block description %} Anasayfa açıklanalar {% endblock %}">
    {% load static %}

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
	<link href="{% static 'css/main.css' %}" rel="stylesheet">
	<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="{% static 'js/html5shiv.js' %}"></script>
    <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'images/ico/apple-touch-icon-57-precomposed.png' %}">

    {% block head %} {% endblock %}
</head>
    {% include 'header.html' %}
    {% block slider %} {% endblock %}
    {% block sidebar %} {% endblock %}
    {% block content %} {% endblock %}
    {% block body %} {% endblock %}
    {% include 'footer.html' %}
    {% block foot %} {% endblock %}
<body>

</body>

</html>

home/templates/product_detail.html
{% extends "homebase.html" %}

{% block title %} {{ product.title }} {% endblock %}
{% block keywords %} {{ product.keywords }} {% endblock %}
{% block description %} {{ product.description }} {% endblock %}
{% block head %}
    {% load static %}
    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="{% static 'css/benim_eklediklerim.css' %}" rel="stylesheet">
    <script src="{% static 'js/benim_eklediklerim.js' %}"></script>
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                {%  include "sidebar.html" %}
                <div class="col-sm-9 padding-right">
                    <div class="product-details"><!--product-details-->
                        <div class="col-sm-5">
                            <div class="view-product" id="maindisplay">
                                <img src="{{ product.image.url}}" id="main-image" alt="" />
                            </div>
                            <div id="similar-product" class="carousel slide" data-ride="carousel">

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    <div class="item active" align="center">
                                        <img src="{{ product.image.url}}" style="height: 100px" onclick="src_change(this.src)">
                                    </div>
                                    {% for rs in images %}
                                        <div class="item" align="center">
                                            <img src="{{ rs.image.url}}" style="height: 100px" alt="" onclick="src_change(this.src)">
                                        </div>
                                    {% endfor %}
                                </div>
                                <!-- Controls -->
                                <a class="left item-control" href="#similar-product" data-slide="prev">
                                    <i class="fa fa-angle-left"></i>
                                </a>
                                <a class="right item-control" href="#similar-product" data-slide="next">
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>

                        </div>
                        <div class="col-sm-7">
                            <div class="product-information"><!--/product-information-->
                                <img src="images/product-details/new.jpg" class="newarrival" alt="" />
                                <h2>{{ product.title}}</h2>
                                <p>Ürün No: {{ product.id}}</p>
                                <img src="images/product-details/rating.png" alt="" />
                                <span>
									<span>TRY {{ product.price}}</span>

                                    <div id="buy-something">
                                        <form action="/order/addtocart/{{ product.id }}" method="post">
                                            {% csrf_token %}
                                            <label>Miktar:</label>
									        <input name="quantity" type="number" value="1" min="0" max="{{ product.amount }}"/>
                                            <button type="submit" class="btn btn-default cart">
										        <i class="fa fa-shopping-cart"></i>	Sepete Ekle
									        </button>
                                        </form>
                                    </div>

								</span>
                                <p><b>Miktar:</b> {{ product.amount}}</p>
                                <p><b>Durum:</b> Yeni</p>
                                <p><b>Yayınevi:</b> {{ product.publisher}}</p>
                                <p><b>Cilt Türü:</b>
                                    {% if product.coverType == "True" %}
                                        Ciltli
                                    {% else %}
                                        Karton Kapak
                                    {% endif %}</p>
                                <p><b>Sayfa Sayısı:</b> {{ product.pages}}</p>
                            </div><!--/product-information-->
                        </div>
                    </div><!--/product-details-->
                    <div class="category-tab shop-details-tab"><!--category-tab-->
                        <div class="col-sm-12">
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#details" data-toggle="tab">Ayrıntılar</a></li>
                                <li><a href="#reviews" data-toggle="tab">Değerlendirmeler</a></li>
                            </ul>
                        </div>
                        <div class="tab-content">
                            <div class="tab-pane fade active in" id="details" >
                                <div class="col-sm-12">
                                    <p>{{ product.detail|safe }}</p>
                                </div>
                            </div>

                            <div class="tab-pane" id="reviews" >
                                <div class="col-sm-6">
                                    <h2 class="title text-center">YORUMLAR</h2>
                                    {% for rs in comments %}
                                        <div id="single_comment" style="font-size: small">
                                            <p><b>Gönderen:</b> {{ rs.user.first_name }} {{ rs.user.last_name }}</p>
                                            <p><b>Gönderme Zamanı:</b> {{ rs.created_at }}</p>
                                            <p><b>Not:</b> {{ rs.rate }}/5</p>
                                            <p><b>{{ rs.subject }}</b></p>
                                            <p>{{ rs.comment }}</p>
                                            <p>-----------------------------</p>
                                        </div>
                                    {% endfor %}
                                </div>
                                <div class="col-sm-6">
                                    <p><b>Lütfen Yorumunuzu Yazın</b></p>
                                    <form action="/product/addcomment/{{ product.id }}" method="post">
                                        {% csrf_token %}
                                        <span>
                                            <input class="input" type="text" name="subject" id="id_subject" placeholder="Konu"/>
										</span>
                                        <textarea class="input" type="text" name="comment" id="id_comment" placeholder="Değerlendirmeniz"></textarea>
                                        <span>
                                            <b>Notunuz: </b></span>

                                        <div class="rate">
                                            <input type="radio" id="star5" name="rate" value="5" />
                                            <label for="star5" title="text">5 yıldız</label>
                                            <input type="radio" id="star4" name="rate" value="4" />
                                            <label for="star4" title="text">4 yıldız</label>
                                            <input type="radio" id="star3" name="rate" value="3" />
                                            <label for="star3" title="text">3 yıldız</label>
                                            <input type="radio" id="star2" name="rate" value="2" />
                                            <label for="star2" title="text">2 yıldız</label>
                                            <input type="radio" id="star1" name="rate" value="1" />
                                            <label for="star1" title="text">1 yıldız</label>
                                        </div>

                                        {% if user.id is not None %}
                                            <button type="submit" class="btn btn-default pull-right" value="Submit"> Gönder </button>
                                        {% else %}
                                            Yorum eklemek için giriş yapmanız gereklidir!
                                        {% endif %}

                                    </form>
                                </div>
                            </div>

                        </div>
                    </div><!--/category-tab-->

                </div>
            </div>
    </section>
{% endblock %}

home/templates/referanslar.html
{% extends "homebase.html" %}

{% block title %} {{ setting.title }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block head %} <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/> {% endblock %}

{% block content %}
    <div class="section">
        <div class="container">
            <div class="row">
                {{ setting.references|safe}}
            </div>
        </div>
    </div>
{% endblock %}